name: Lint
'on':
  - push
  - pull_request
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install editorconfig-checker
        run: |
          gh release download --pattern "*linux-amd64.tar.gz" --dir /tmp
          tar xvzf /tmp/ec-linux-amd64.tar.gz -C /tmp
          chmod +x /tmp/bin/ec-linux-amd64
          mv /tmp/bin/ec-linux-amd64 /usr/local/bin/ec
        env:
          GH_REPO: editorconfig-checker/editorconfig-checker
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Run linter
        run: |
          make version
          make lint
